### ISSUE TITLE
Migration to Anchorage

### ISSUE THREAD

**Issue by mmontour1306** [bobanetwork/v3-boba#17]
We need a way of converting our existing L2 chains into Anchorage-enabled versions while preserving existing users and applications as much as possible. This procedure must be documented and tested well in advance of the actual event, and we must provide an opportunity for developers and community members to identify any cases in which applications will break due to the architectural changes in Anchorage (such as having fixed-time blocks with multiple transactions vs. auto-mining a block per single Tx) and/or in the Hybrid Compute protocol (TBD).

I anticipate that we will follow Optimism's general strategy of maintaining an L2geth node in read-only mode, behind a proxy service which uses it to satisfy any queries for old blocks while redirecting other traffic to the new Bedrock-mode sequencer. This will have to be integrated with any other proxy servers we are using, such as to split query load across multiple Replica nodes.

Because we are transitioning both legacy->Bedrock and l2geth->Erigon, we can not directly use Optimism's approach of manipulating the state within the underlying database of the l2geth node. However it may make sense for us to perform this step as part of a larger process e.g. (draft, subject to change):

 - Deploy the new L1 contracts to support Anchorage, configured with appropriate permissions and ownership
 - Ensure that we have L1 accounts set up to collect gas fees from the new L2
 - At the start of a scheduled maintenance window, cut off all incoming traffic to the old l2geth node and wait for the system to settle (including a forced push of the Batch Submitter to ensure that all transactions have been rolled up to L1)
 - Shut down the l2geth node
 - Run Optimism's migration tool (+ any enhancements for our custom predeploy contracts) to write a Bedrock Transition Block into the l2geth database
 - Bring up l2geth in a read-only mode using the transitioned database
 - Perform a state dump of the Bedrock Transition Block
 - Convert this state dump into an Erigon-compatible genesis.json file
 - Initialize a blank Erigon node from this genesis file
 - Have the Erigon node "mine" empty blocks starting from the genesis block up to and including the block number of the Bedrock Transition Block / L2 Chain Inception
 - Once Erigon has reached the L2 Chain Inception point, enable the Bedrock services and allow op-node to control block derivation from that point onward
 - After verifying that the new system is successfully deriving blocks and posting batches to L1, re-enable incoming client traffic through the proxy and into the new Erigon node.

We need to make sure that in-progress withdrawals from the old system can still be completed after the upgrade, and that any pending L1->L2 deposits directed toward the old system are processed appropriately (ideally delivered as intended, or refunded on L1 if that is not possible for any reason).

We need to make sure that any gas fees or other fees collected on the old L2 are either migrated to the new system or are paid out prior to the conversion.

**Comment by boyuan-chen** [comment]
The docs for the migration: https://github.com/bobanetwork/v3-anchorage/tree/develop/boba-chain-ops#migration

**Comment by InoMurko** [comment]
Please re-open if things are missing.
