### ISSUE TITLE
Repo cleanup

### ISSUE THREAD

**Issue by mmontour1306** [bobanetwork/v3-boba#6]
A few cleanup tasks:

1.  Set the default branch to "boba-develop" in the v3-boba repository and in all of its v3-xxx submodules
2.  Force-sync the "main" branch in our v3-erigon-lib to the upstream ledgerwatch:erigon-lib main branch (I can't do this myself as it says the branch is protected)
3.  Archive the previous "boba-v3" repository and move any open issues over to this "v3-boba" repo.
4.  Remove the 'bedrock' directory and its submodules (erigon, reference-optimistic-geth) from our main "boba" repository now that we have the v3-xxx versions of them.
5.  For now, I would like to remove the "boba-main" branch from all of our v3-xxx repositories. These branches can be re-created from the corresponding boba-develop branches when we start working on the packaging, versioning, and release-candidate workflow for the new system.

**Comment by wsdt** [comment]
1. ~Set the default branch to "boba-develop" in the v3-boba repository and in all of its v3-xxx submodules~
2. ~Force-sync the "main" branch in our v3-erigon-lib to the upstream ledgerwatch:erigon-lib main branch (I can't do this myself as it says the branch is protected)~
3. ~Archive the previous "boba-v3" repository and move any open issues over to this "v3-boba" repo.~
4. ~Remove the 'bedrock' directory and its submodules (erigon, reference-optimistic-geth) from our main "boba" repository now that we have the v3-xxx versions of them.~
5. ~For now, I would like to remove the "boba-main" branch from all of our v3-xxx repositories. These branches can be re-created from the corresponding boba-develop branches when we start working on the packaging, versioning, and release-candidate workflow for the new system.~
